In [11]:
from datasets import load_dataset
import pandas as pd

In [ ]:
dataset = load_dataset(
    "McAuley-Lab/Amazon-Reviews-2023",
    "raw_review_Kindle_Store",
    split="full",
    streaming=True,
    trust_remote_code=True
)

reviews = []
for i, x in enumerate(dataset):
    reviews.append(x)
    if i >= 10000:
        break

In [38]:
dataset_meta = load_dataset(
    "McAuley-Lab/Amazon-Reviews-2023",
    "raw_meta_Kindle_Store",
    split="full",
    streaming=True,
    trust_remote_code=True
)

metadata = []
for i, x in enumerate(dataset_meta):
    metadata.append(x)
    if i >= 10000:
        break

In [40]:
df_reviews = pd.DataFrame(reviews)

df_reviews.head(5)

,rating,title,text,images,asin,parent_asin,user_id,timestamp,helpful_vote,verified_purchase
0,5.0,excellent writer reminds me of Clive Cussler,GRUMLEY is on par with Clive Cussler and his D...,[],B00LXRJICK,B00LXRJICK,AFKZENTNBQ7A7V7UXW5JJI6UGRYQ,1427541413000,0,False
1,3.0,Alright book,The book Fade was not my favorite but was a go...,[],B073DFP8VC,B073DFP8VC,AHGTHCERTEZUXNBLJ5SWHK2CDLXA,1504226946142,0,True
2,5.0,Hats off to Fern Michaels for all her great ac...,I have been a fan of this author for many year...,[],B07QVH25KX,B07QVH25KX,AHFY2QSS6PK5MHSYZFI6TXUYNPLQ,1644883955777,0,True
3,5.0,Great read,This book is more than just about a dog and a ...,[],B004Y1NWQU,B004Y1NWQU,AHFY2QSS6PK5MHSYZFI6TXUYNPLQ,1363027885000,0,False
4,5.0,Add to legend f Arthur,Good twist on the ledgen of King<br />Arthur !...,[],B08M993CNC,B08M993CNC,AFWHJ6O3PV4JC7PVOJH6CPULO2KQ,1637557512064,0,True

In [41]:
df_metadata = pd.DataFrame(metadata)

df_metadata.head(5)

,main_category,title,average_rating,rating_number,features,description,price,images,videos,store,categories,details,parent_asin,bought_together,subtitle,author
0,Buy a Kindle,The Palace (Chateau Book 4),4.7,970,[A line was drawn in the sand.I made my choice...,[],0.0,"{'hi_res': [None], 'large': ['https://m.media-...","{'title': [], 'url': [], 'user_id': []}",Penelope Sky (Author) Format: Kindle Edition,"[Kindle Store, Kindle eBooks, Romance]","{""Publisher"": ""Hartwick Publishing (May 25, 20...",B08XPZPFY4,None,Kindle Edition,{'avatar': 'https://m.media-amazon.com/images/...
1,Buy a Kindle,Microsoft PowerPoint 2016 2013 2010 2007 Tips ...,4.3,35,"[Paperback versions are also available, includ...","[From the Author, Amelia Griggs is an Instruct...",0.0,"{'hi_res': [None], 'large': ['https://m.media-...","{'title': [], 'url': [], 'user_id': []}",Amelia Griggs (Author) Format: Kindle Edition,"[Kindle Store, Kindle eBooks, Computers & Tech...","{""Publication date"": ""June 2, 2018"", ""Language...",B07DH1LF1K,None,[Print Replica] Kindle Edition,{'avatar': 'https://m.media-amazon.com/images/...
2,Buy a Kindle,Ill Wind (Anna Pigeon Mysteries Book 3),4.4,1628,"[Lately, visitors to Mesa Verde have been brin...","[From Publishers Weekly, Barr lands another su...",7.99,"{'hi_res': [None], 'large': ['https://m.media-...","{'title': [], 'url': [], 'user_id': []}",Nevada Barr (Author) Format: Kindle Edition,"[Kindle Store, Kindle eBooks, Mystery, Thrille...","{""Publisher"": ""Berkley; Reissue edition (March...",B0022Q8CTQ,None,Kindle Edition,{'avatar': 'https://m.media-amazon.com/images/...
3,Buy a Kindle,30 Healthy Easy Quick Lentil Recipes (Brad Arm...,3.8,47,"[If improved health you are seeking, look no f...",[],0.0,"{'hi_res': [None], 'large': ['https://m.media-...","{'title': [], 'url': [], 'user_id': []}",Brad Armstrong (Author) Format: Kindle Edition,"[Kindle Store, Kindle eBooks, Health, Fitness ...","{""Publisher"": ""Brad Armstrong (March 10, 2013)...",B00BS56MLC,None,Kindle Edition,{'avatar': 'https://m.media-amazon.com/images/...
4,Buy a Kindle,The Road Home,4.5,475,"[In one of Jim Harrison’s greatest works, five...","[Review, ""A graceful novel...To read this book...",10.44,"{'hi_res': [None], 'large': ['https://m.media-...","{'title': [], 'url': [], 'user_id': []}",Jim Harrison (Author) Format: Kindle Edition,"[Kindle Store, Kindle eBooks, Literature & Fic...","{""Publisher"": ""Atlantic Monthly Press (Decembe...",B00155EZRS,None,Kindle Edition,{'avatar': 'https://m.media-amazon.com/images/...

In [30]:
df_reviews.describe(), df_reviews.info()

<class 'pandas.DataFrame'>
RangeIndex: 1001 entries, 0 to 1000
Data columns (total 10 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   rating             1001 non-null   float64
 1   title              1001 non-null   str
 2   text               1001 non-null   str
 3   images             1001 non-null   object
 4   asin               1001 non-null   str
 5   parent_asin        1001 non-null   str
 6   user_id            1001 non-null   str
 7   timestamp          1001 non-null   int64
 8   helpful_vote       1001 non-null   int64
 9   verified_purchase  1001 non-null   bool
dtypes: bool(1), float64(1), int64(2), object(1), str(5)
memory usage: 604.7+ KB

(            rating     timestamp  helpful_vote
 count  1001.000000  1.001000e+03   1001.000000
 mean      4.449550  1.501922e+12      0.781219
 std       0.915261  8.135508e+10      2.785155
 min       1.000000  1.313013e+12      0.000000
 25%       4.000000  1.448233e+12      0.000000
 50%       5.000000  1.483057e+12      0.000000
 75%       5.000000  1.561775e+12      1.000000
 max       5.000000  1.677668e+12     51.000000,
 None)

In [32]:
df_metadata.describe(), df_metadata.info()

<class 'pandas.DataFrame'>
RangeIndex: 1001 entries, 0 to 1000
Data columns (total 16 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   main_category    1001 non-null   str
 1   title            1001 non-null   str
 2   average_rating   1001 non-null   float64
 3   rating_number    1001 non-null   int64
 4   features         1001 non-null   object
 5   description      1001 non-null   object
 6   price            1001 non-null   str
 7   images           1001 non-null   object
 8   videos           1001 non-null   object
 9   store            1001 non-null   str
 10  categories       1001 non-null   object
 11  details          1001 non-null   str
 12  parent_asin      1001 non-null   str
 13  bought_together  0 non-null      object
 14  subtitle         984 non-null    str
 15  author           855 non-null    str
dtypes: float64(1), int64(1), object(6), str(8)
memory usage: 1.4+ MB

(       average_rating  rating_number
 count     1001.000000    1001.000000
 mean         4.297403     624.243756
 std          0.551845    5136.877916
 min          1.000000       1.000000
 25%          4.100000      13.000000
 50%          4.400000      47.000000
 75%          4.600000     214.000000
 max          5.000000  138549.000000,
 None)

In [26]:
df_reviews.isna().sum(), df_metadata.isna().sum()

(rating               0
 title                0
 text                 0
 images               0
 asin                 0
 parent_asin          0
 user_id              0
 timestamp            0
 helpful_vote         0
 verified_purchase    0
 dtype: int64,
 main_category         0
 title                 0
 average_rating        0
 rating_number         0
 features              0
 description           0
 price                 0
 images                0
 videos                0
 store                 0
 categories            0
 details               0
 parent_asin           0
 bought_together    1001
 subtitle             17
 author              146
 dtype: int64)

In [ ]:
df_merged = df_reviews.merge(df_metadata, on ="parent_asin", how = "inner")
df_merged.head(5)

,rating,title_x,text,images_x,asin,parent_asin,user_id,timestamp,helpful_vote,verified_purchase,...,description,price,images_y,videos,store,categories,details,bought_together,subtitle,author
0,4.0,Some great tips on getting healthy,Some great tips on getting healthy. Great star...,[],B00QMUBB0K,B00QMUBB0K,AEINY4XOINMMJCK5GZ3M6MMHBN6A,1445287011000,0,True,...,[],4.99,"{'hi_res': [None], 'large': ['https://m.media-...","{'title': [], 'url': [], 'user_id': []}","Dr. Jyothi Shenoy (Author), Lori Wenger (Edit...","[Kindle Store, Kindle eBooks, Health, Fitness ...","{""Publisher"": ""Lose Weight Now Ltd. (December ...",None,Kindle Edition,{'avatar': 'https://m.media-amazon.com/images/...
1,5.0,Touching !,i got this book from amazon as a freebie (or m...,[],B00C8BV10W,B00C8BV10W,AHGAOIZVODNHYMNCBV4DECZH42UQ,1378581448000,1,True,...,"[Review, Semifinalist in Literary Fiction at T...",0.0,"{'hi_res': [None], 'large': ['https://m.media-...","{'title': [], 'url': [], 'user_id': []}",Kim Cano (Author) Format: Kindle Edition,"[Kindle Store, Kindle eBooks, Literature & Fic...","{""Publication date"": ""April 5, 2013"", ""Languag...",None,Kindle Edition,{'avatar': 'https://m.media-amazon.com/images/...
2,5.0,Wow!,I absolutely loved this book! I could not put...,[],B087ZXSPGJ,B087ZXSPGJ,AEW55ZDSPC6HOXZ2RK5MCT7OM5WQ,1612906611122,0,True,...,"[Amazon.com Review, An Amazon Best Book of Feb...",11.99,"{'hi_res': [None], 'large': ['https://m.media-...","{'title': [], 'url': [], 'user_id': []}",Kristin Hannah (Author) Format: Kindle Edition,"[Kindle Store, Kindle eBooks, Literature & Fic...","{""Publisher"": ""St. Martin's Press (February 2,...",None,Kindle Edition,{'avatar': 'https://m.media-amazon.com/images/...
3,5.0,awesomely fun to read...,I won a copy of this book from an author event...,[],B014K1BR4C,B014K1BR4C,AFFZVSTUS3U2ZD22A2NPZSKOCPGQ,1455582556000,0,False,...,"[Review, ""If Amy Schumer and Janet Evanovitch ...",0.0,"{'hi_res': [None], 'large': ['https://m.media-...","{'title': [], 'url': [], 'user_id': []}",Ron Peterman (Author) Format: Kindle Edition,"[Kindle Store, Kindle eBooks, Romance]","{""Publisher"": ""Robyn Peterman (September 22, 2...",None,Kindle Edition,{'avatar': 'https://m.media-amazon.com/images/...
4,5.0,Five well earned stars...,Loved book two. Levy grew as a character. I le...,[],B06XQ85LY5,B06XQ85LY5,AFO3G62P2JXCNMWZTAIB56KPG56A,1490902634000,0,False,...,"[Review, ""This series gets, better, and, bette...",0.0,"{'hi_res': [None], 'large': ['https://m.media-...","{'title': [], 'url': [], 'user_id': []}",McKenzie Hunter (Author) Format: Kindle Edition,"[Kindle Store, Kindle eBooks, Mystery, Thrille...","{""Publisher"": ""Sky Publishing (March 17, 2017)...",None,Kindle Edition,{'avatar': 'https://m.media-amazon.com/images/...

In [47]:

df_merged.info(), df_merged.describe()

<class 'pandas.DataFrame'>
RangeIndex: 75 entries, 0 to 74
Data columns (total 25 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   rating             75 non-null     float64
 1   title_x            75 non-null     str
 2   text               75 non-null     str
 3   images_x           75 non-null     object
 4   asin               75 non-null     str
 5   parent_asin        75 non-null     str
 6   user_id            75 non-null     str
 7   timestamp          75 non-null     int64
 8   helpful_vote       75 non-null     int64
 9   verified_purchase  75 non-null     bool
 10  main_category      75 non-null     str
 11  title_y            75 non-null     str
 12  average_rating     75 non-null     float64
 13  rating_number      75 non-null     int64
 14  features           75 non-null     object
 15  description        75 non-null     object
 16  price              75 non-null     str
 17  images_y           75 non-null     object
 18  videos             75 non-null     object
 19  store              75 non-null     str
 20  categories         75 non-null     object
 21  details            75 non-null     str
 22  bought_together    0 non-null      object
 23  subtitle           75 non-null     str
 24  author             75 non-null     str
dtypes: bool(1), float64(2), int64(3), object(7), str(12)
memory usage: 158.8+ KB

(None,
           rating     timestamp  helpful_vote  average_rating  rating_number
 count  75.000000  7.500000e+01     75.000000       75.000000      75.000000
 mean    4.506667  1.513028e+12      0.520000        4.382667    5330.640000
 std     0.949727  9.052139e+10      1.131371        0.234448   17087.844444
 min     1.000000  1.353614e+12      0.000000        3.600000      15.000000
 25%     4.000000  1.429116e+12      0.000000        4.200000     355.500000
 50%     5.000000  1.503407e+12      0.000000        4.400000    1006.000000
 75%     5.000000  1.596731e+12      1.000000        4.500000    2526.000000
 max     5.000000  1.664997e+12      7.000000        4.800000  138549.000000)

In [50]:
len(df_reviews), len(df_metadata), len(df_merged)

(10001, 10001, 75)

In [52]:
df_filtered = df_merged[[
    "parent_asin",
    "title_x",
    "title_y",
    "description",
    "features",
    "text",
    "main_category",
    "rating",
    "verified_purchase"
]].copy()

df_filtered = df_filtered.rename(columns={
    "title_x": "review_title",
    "title_y": "product_title",
    "text": "review_text"
})

In [53]:
df_filtered.head(5)

,parent_asin,review_title,product_title,description,features,review_text,main_category,rating,verified_purchase
0,B00QMUBB0K,Some great tips on getting healthy,Lose Weight Fast: Over 50 Incredible Weight Lo...,[],"[Are You Sick Of Being Overweight?, This book ...",Some great tips on getting healthy. Great star...,Buy a Kindle,4.0,True
1,B00C8BV10W,Touching !,A Widow Redefined,"[Review, Semifinalist in Literary Fiction at T...",[Amy White is one of the luckiest women alive....,i got this book from amazon as a freebie (or m...,Buy a Kindle,5.0,True
2,B087ZXSPGJ,Wow!,The Four Winds: A Novel,"[Amazon.com Review, An Amazon Best Book of Feb...","[""The Bestselling Hardcover Novel of the Year....",I absolutely loved this book! I could not put...,Buy a Kindle,5.0,True
3,B014K1BR4C,awesomely fun to read...,Switching Hour: Magic and Mayhem Book One,"[Review, ""If Amy Schumer and Janet Evanovitch ...",[Released from the magic pokey and paroled wit...,I won a copy of this book from an author event...,Buy a Kindle,5.0,False
4,B06XQ85LY5,Five well earned stars...,Obsidian Magic (Legacy Series Book 2),"[Review, ""This series gets, better, and, bette...",[The only thing standing between me and death ...,Loved book two. Levy grew as a character. I le...,Buy a Kindle,5.0,False

In [73]:
df_filtered["document"] = (
    df_filtered["product_title"].fillna("") + " " +
    df_filtered["description"].fillna("") + " " +
    df_filtered["features"].fillna("") + " " +
    df_filtered["review_text"].fillna("")
)

In [74]:
df_filtered

,parent_asin,review_title,product_title,description,features,review_text,main_category,rating,verified_purchase,document
0,B00QMUBB0K,Some great tips on getting healthy,Lose Weight Fast: Over 50 Incredible Weight Lo...,,Are You Sick Of Being Overweight? This book is...,Some great tips on getting healthy. Great star...,Buy a Kindle,4.0,True,Lose Weight Fast: Over 50 Incredible Weight Lo...
1,B00C8BV10W,Touching !,A Widow Redefined,Review Semifinalist in Literary Fiction at The...,Amy White is one of the luckiest women alive.A...,i got this book from amazon as a freebie (or m...,Buy a Kindle,5.0,True,A Widow Redefined Review Semifinalist in Liter...
2,B087ZXSPGJ,Wow!,The Four Winds: A Novel,Amazon.com Review An Amazon Best Book of Febru...,"""The Bestselling Hardcover Novel of the Year.""...",I absolutely loved this book! I could not put...,Buy a Kindle,5.0,True,The Four Winds: A Novel Amazon.com Review An A...
3,B014K1BR4C,awesomely fun to read...,Switching Hour: Magic and Mayhem Book One,"Review ""If Amy Schumer and Janet Evanovitch ha...",Released from the magic pokey and paroled with...,I won a copy of this book from an author event...,Buy a Kindle,5.0,False,Switching Hour: Magic and Mayhem Book One Revi...
4,B06XQ85LY5,Five well earned stars...,Obsidian Magic (Legacy Series Book 2),"Review ""This series gets better and better wit...",The only thing standing between me and death i...,Loved book two. Levy grew as a character. I le...,Buy a Kindle,5.0,False,"Obsidian Magic (Legacy Series Book 2) Review ""..."
...,...,...,...,...,...,...,...,...,...,...
70,B00OJONHQ2,with more effort it could have been a 5 star read,Packing Double: A Bedlam Butchers MC Romance (...,,When Kitty hears about the notorious ‘panty ra...,"This was the best book of the series so far, B...",Buy a Kindle,3.0,False,Packing Double: A Bedlam Butchers MC Romance (...
71,B002YKOXJ8,"Excellent, Fun Series to Read",Undead and Unreturnable: A Queen Betsy Novel,From Booklist In Davidson's latest Undead romp...,"As if she needed yet another reason to shop, Q...",Mary Janice Davidson writes fiction based on e...,Buy a Kindle,5.0,True,Undead and Unreturnable: A Queen Betsy Novel F...
72,B00LD1RZ3A,One of my favorite authors and I loved it so m...,Less Than Hero,"Unknown ""Wickedly sharp and wildly entertainin...",With the razor-sharp satire that earned him ra...,One of my favorite authors and I loved it so m...,Buy a Kindle,5.0,True,"Less Than Hero Unknown ""Wickedly sharp and wil..."
73,B00CO7FIQ8,Three Stars,The Bear: A Novel,From Booklist When a young couple in Canada’s ...,A powerful suspense novel narrated by a young ...,Delivery prompt.,Buy a Kindle,3.0,True,The Bear: A Novel From Booklist When a young c...
74,B00AKZO1HI,Great Romantic Suspense!,The Forever Stone (The Dumont Chronicles Book 1),"Review ""Believable! Just the right combination...",The paperweight—a summons to courage . . . A n...,"Thought I had already reviewed this book, but ...",Buy a Kindle,5.0,True,The Forever Stone (The Dumont Chronicles Book ...